[package]
name = "tomatentimer"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.25.0"
egui = "0.25.0"
egui_extras = { version = "0.25.0", features = ["image"]}
env_logger = "0.11.1"
iced = { version = "0.10.0", features = ["smol", "debug", "svg"] }
notify-rust = "4"
slint = "1.4.1"
